POST localhost:8080/
Content-Type: application/json

{
  "user_id":"123",
  "postpaid_limit":123,
  "spp":123,
  "shipping_fee":123,
  "return_fee":123
}

###

POST localhost:8080/
Content-Type: application/json

{
  "user_id":"1234",
  "postpaid_limit":123
}

###
POST localhost:8080/
Content-Type: application/json

{
  "user_id":"1234",
  "spp":123,
  "shipping_fee":123,
  "return_fee":123
}

###