POST localhost:8080/
Content-Type: application/json

{
  "user_id":"user1",
  "postpaid_limit":100,
  "spp":40,
  "shipping_fee":120,
  "return_fee":125
}

###

POST localhost:8080/
Content-Type: application/json

{
  "user_id":"1234",
  "postpaid_limit":123
}

###
POST localhost:8080/
Content-Type: application/json

{
  "user_id":"1234",
  "spp":123,
  "shipping_fee":123,
  "return_fee":123
}

###

GET localhost:8090/?user_id=1234

###

GET localhost:8090/backup/

###